//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweetCatApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SweetCatApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Profil.
        /// </summary>
        internal static string Add_Profile_Text_Button {
            get {
                return ResourceManager.GetString("Add_Profile_Text_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzupełnij dane profilu.
        /// </summary>
        internal static string AddPetsProfile_FillProfil_Text_Label {
            get {
                return ResourceManager.GetString("AddPetsProfile_FillProfil_Text_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dotknij, żeby zmienić zdjęcie profilowe.
        /// </summary>
        internal static string AddPetsProfile_Photo_Text_Label {
            get {
                return ResourceManager.GetString("AddPetsProfile_Photo_Text_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bengal Cat.
        /// </summary>
        internal static string Bengal_Text_Label {
            get {
                return ResourceManager.GetString("Bengal_Text_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Shorthair.
        /// </summary>
        internal static string Brithis_Blue_Text_Label {
            get {
                return ResourceManager.GetString("Brithis_Blue_Text_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj Profil.
        /// </summary>
        internal static string Edit_Profile_Text_Button {
            get {
                return ResourceManager.GetString("Edit_Profile_Text_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mainecoon.
        /// </summary>
        internal static string Mainecoon_Text_Label {
            get {
                return ResourceManager.GetString("Mainecoon_Text_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Pets profile .
        /// </summary>
        internal static string Pets_Profil_Text_Button {
            get {
                return ResourceManager.GetString("Pets_Profil_Text_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz.
        /// </summary>
        internal static string PetsProfile_Text_Label {
            get {
                return ResourceManager.GetString("PetsProfile_Text_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz.
        /// </summary>
        internal static string Title_Text_Picker {
            get {
                return ResourceManager.GetString("Title_Text_Picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string welcomeText {
            get {
                return ResourceManager.GetString("welcomeText", resourceCulture);
            }
        }
    }
}
